Update model.py
WyllasSidjeno/Orion pull request #12
Opened 2023-02-27 15:33 UTC by Djou-Karl

Ajout de class Population et méthode deplete_energy  dans la classe joueur, ajout des variables nécessaires pour compiler

2023-02-27 15:42 UTC, WyllasSidjeno requested changes
Ajouter Always Int a self.energie et self.consommationJoueur et où nécessaire.

2023-02-27 20:26 UTC, WyllasSidjeno requested changes
Commentaire additionelle. Pas obligé de le "fix", mais une petite remarque additionelle :)

2023-02-27 20:26 UTC, WyllasSidjeno commented on Orion_client/model/model.py
> +    def setConsommation(self, consommation):
Setter and getter non nécessaire en python.

2023-02-27 20:26 UTC, WyllasSidjeno commented on Orion_client/model/model.py
> +    def getConsommation(self):
Setter and getter non nécessaire en python.

2023-02-27 20:28 UTC, WyllasSidjeno approved these changes

2023-02-28 13:35 UTC, closed without merging

2023-02-28 13:35 UTC, Djou-Karl commented
nouveau push